language: go
go: 1.1
services:
  - memcache # github.com/teltech/revel/cache
install:
  - export PATH=$PATH:$HOME/gopath/bin
  # Annoyingly, we can not use go get revel/... because references to app/routes package fail
  - go get -v github.com/teltech/revel/revel
  - go get -v github.com/teltech/revel/cache
  - go get -v github.com/teltech/revel/harness
  - go get -v github.com/coopernurse/gorp
  - go get -v code.google.com/p/go.crypto/bcrypt
  - go get -v github.com/mattn/go-sqlite3
  - go get -v github.com/robfig/cron
  - go get -v github.com/robfig/goauth2/oauth
  - go get -v github.com/mrjones/oauth
script:
  - go test github.com/teltech/revel
  - go test github.com/teltech/revel/cache
  - go test github.com/teltech/revel/harness

  # Ensure the new-app flow works (plus the other commands).
  - revel new     my/testapp
  - revel test    my/testapp
  - revel clean   my/testapp
  - revel build   my/testapp build/testapp
  - revel package my/testapp

  # Build & run the sample apps
  - revel test github.com/teltech/revel/samples/booking
  - revel test github.com/teltech/revel/samples/chat
  - revel test github.com/teltech/revel/samples/validation
  - revel test github.com/teltech/revel/samples/chat
